name: Deploy
on:
  workflow_dispatch

jobs:
  deploy:
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'main' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cargo
          sudo apt-get install python3

      - name: Build executable
        run: |
          cd accounter
          cargo build -r

      - name: Tag release
        id: release-tag
        uses: phish108/autotag-action@1.1.51
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release-tag.outputs.new-tag }}
          files: |
            ./accounter/target/release/accounter

