name: Verify PR
on:
  pull_request:
    types:
      - opened
    paths:
      - "requests/*.csv"

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "accounter"
          out-file-path: "./accounter-exe"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1

      - name: Verify
        run: |
          chmod +x ./accounter-exe/accounter
          CHANGED=${{ steps.changed-files.outputs.all_changed_files }}
          NUM_CHANGED=$(wc -w <<< "$CHANGED")
          if [ $NUM_CHANGED -ne 1 ]; then
            echo "::error Too many files - only submit one file"
            exit 1
          fi
          ./accounter-exe/accounter --database ./account.sqlite --filename $CHANGED --user ${{ github.event.pull_request.user.login }} --validate

