name: Update Database
on:
  push:
    branches:
      - main
    paths:
      - "requests/*.csv"

jobs:
  update-database:
    if: |
      github.event_name == 'push' &&
      github.ref_name == 'main' &&
      github.actor != 'nd-0r-test' &&
      github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DATABASE_UPDATE }}
          fetch-depth: 2

      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "accounter"
          out-file-path: "./accounter-exe"
          token: ${{ secrets.DATABASE_UPDATE }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v29.0.1

      - name: Update database
        run: |
          chmod +x ./accounter-exe/accounter
          git config --global user.email "aorals2@illinois.edu"
          git config --global user.name "Andrew Orals"
          CHANGED=${{ steps.changed-files.outputs.all_changed_files }}
          NUM_CHANGED=$(wc -w <<< "$CHANGED")
          if [ $NUM_CHANGED -ne 1 ]; then
            echo "::error Too many files - only submit one file"
            exit 1
          fi
          ./accounter-exe/accounter --database ./account.sqlite --filename $CHANGED --user "$(git --no-pager log --pretty=format:'%an' --diff-filter=A -- ./LICENSE)" --markdown ./README.md > ./balance.csv
          git rm $CHANGED
          git add README.md balance.csv account.sqlite
          git commit -m "ACCOUNTANT: add transaction"
          git push https://nd-0r-test:${{ secrets.DATABASE_UPDATE }}@github.com/aaaapartment/apartment-accounting.git

